# .github/workflows/build.yml
name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install Dependencies
      run: npm install
    
    - name: Build
      run: npm run build
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: miniprogram
        path: dist/